spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: greet-api
          uri: lb://Greet-API
          predicates:
            - Path=/greet
        - id: welcome-api
          uri: lb://Welcome-Api
          predicates:
            - Path=/welcome
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 2222